### ISSUE TITLE
Update USGS Geosearch to latest version & Pop-up selection issue

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/fim-js#156]
Update to latest version to include address autocomplete.
When typing in the search box, the suggestions pop up behind the modal:
![image](https://user-images.githubusercontent.com/12058013/30329028-1b1d354a-979f-11e7-81cc-015a1d2014c5.png)

**Comment by njestes** [comment]
We think the issue is happening because we want the geosearch to popup over the site popup when displayed. So a z-index was added to the geosearch modal. It brings the geosearch modal forward but leaves the list of suggestions behind. Thinking some @mitch-wim 👀 might be good for this.
