### ISSUE TITLE
splash screen (?) for flash player version check

### ISSUE THREAD

**Issue by mhkim01** [USGS-WiM/fim-js#196]
![image](https://user-images.githubusercontent.com/15948427/31292086-0716c188-aaa0-11e7-9c88-f832e6cdb48c.png)

user writes: "-when you go to the mapper site form a mobile device, the first mostly empty gray page that comes up with the adobe flash player message and the FIM link to the mobile app​, that text on the gray background is super tiny on a an iphone and ipad. If you didn't know the FIM link is there you would only see it to click on it IF the user actually zooms in to read the message. Otherwise it looks like every other adobe flash message and many people are used to seeing those and figure it is a dead end and close it with out looking closer. Can you enlarge that text and/or change color back ground or otherwise draw more obvious  attention to the fact that it isn't a dead end?

**Comment by HansVraga** [comment]
Make changes in FIM repo: https://github.com/USGS-WiM/FIM/tree/staging/html-template
