### ISSUE TITLE
Update Printing method

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/fim-js#200]
(for reference) https://github.com/USGS-WiM/FIM/issues/124

**Comment by HansVraga** [comment]
Single site looks good, Multi-site still in progress

**Comment by HansVraga** [comment]
Tested on 8Aug for single and multi site and getting error:
![image](https://user-images.githubusercontent.com/12058013/62707923-e6921d80-b9b7-11e9-9dc5-b54ae1123610.png)

**Comment by njestes** [comment]
@hans I believe that error ☝️ is fixed with the site loading issues. Can you take another look and see if you can replicate it or we can check that off. 

There are new issues with print now. It doesn't seem to like certain sites. Might be multi-sites. Looking into it.

**Comment by njestes** [comment]
@mhkim01 this error Hans included a screenshot for up there ☝️ is due to some libraries not having page 1 info. Do (should) all sites have page 1 print info on Mario currently? One example is site 
03335500 in Indiana. Should that site have page 1 info?

**Comment by mhkim01** [comment]
@njestes 03335500 does have page 1 print info on fim.wim (is that Mario?) server currently. Not all have page 1 print info, for example furnished map sites, https://fim.wim.usgs.gov/fim/?site_no=13206000, will not have it because we were waiting for furnished map print page layout.

**Comment by njestes** [comment]
@mhkim01 Sounds good. Will the furnished sites not have the same layout? Do we have any idea what that's going to look like? I remember talking about having a different banner but nothing beyond that.
