### ISSUE TITLE
Multi-site Print Products

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/fim-js#202]
Address issue described in: https://github.com/USGS-WiM/FIM/issues/88

**Comment by HansVraga** [comment]
New print method makes this issue obsolete.

**Comment by mhkim01** [comment]
I like the solution mentioned in https://github.com/USGS-WiM/FIM/issues/88 for page 2 map title.
However, I would modify the title to "Flood-Inundation Map for multiple streamgages near [community name], [state]". Then and leave the subtitle as is.

**Comment by mhkim01** [comment]
the word "near" is used often in [community names]. let's go back to what Hans suggested and use "around". So, "Flood-Inundation Map for multiple streamgages around [community name], [state]".
