### ISSUE TITLE
Link leads to 404

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/fim-js#241]
Clicking on the circled "?" takes me here: https://fim.wim.usgs.gov/fim-js-dev/NONE and shows a 404

![image](https://user-images.githubusercontent.com/12058013/39950630-8bf09a9a-5550-11e8-8364-3cb6cbfa232f.png)

**Comment by njestes** [comment]
@HansVraga can you point me to which library this is and what the link looks like? These '?'s should point to the report and all the libraries I have tried have worked, so I need to see what is up with this library specifically, and then determine if it will happen with others or it's just an issue with this one.

**Comment by njestes** [comment]
The issue also affects the report link (another 404), need to just use similar wording to the Flash mapper. "No report available"

**Comment by njestes** [comment]
also need to hide the thumbnail if no report. right now it's a broken image
