### ISSUE TITLE
Marion, IN: grids do not show when check marked "View Grid"

### ISSUE THREAD

**Issue by mhkim01** [USGS-WiM/fim-js#242]
but grids show up on flash mapper without issues.

![image](https://user-images.githubusercontent.com/15948427/40019670-e7bdc818-578d-11e8-979b-b495b9d07f36.png)

**Comment by njestes** [comment]
Tracked down the issue. Only happening with libraries that also have breach grids. Need to draw separate layers for breach grids and flood poly grids.
