### ISSUE TITLE
Add vertical line marking transition between 'real' and 'predicted' values in Hydrograph

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/fim-js#252]

**Comment by HansVraga** [comment]
![image](https://user-images.githubusercontent.com/12058013/44170547-aef2dd00-a0a5-11e8-891e-b786824a560c.png)

**Comment by mitch-wim** [comment]
Do we need this if we have this feature: https://cl.ly/e260df45480e

**Comment by HansVraga** [comment]
we're going to proceed without this for now
