### ISSUE TITLE
Stand up new 10.6 ArcEnterprise Server for FIM in WMA subaccount

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/fim-js#291]
Currently, FIM Map services needs are being served by gis.wim.usgs.gov. It should be it's own AGS system within the WMA subaccount. There is also print functionality issues we hope to address by using the newest available version of ArcEnterprise.

**Comment by aaronstephenson** [comment]
Email request sent to Zivaro, Service Request Number 869.

**Comment by aaronstephenson** [comment]
@HansVraga What FQDN do you want for this? fim.wim.usgs.gov?

**Comment by HansVraga** [comment]
Status update Z-No has been bouncing Licensing questions off of DoI via @aaronstephenson - they are still working on building this system.

**Comment by HansVraga** [comment]
@aaronstephenson is it possible to be able to publish to this new server from our GIS Jump Server (jump.wim.usgs.gov)

**Comment by aaronstephenson** [comment]
Yes, should work right off the bat.

**Comment by DanielJBeckman** [comment]
Test server is setup and volumes are mounted.  Meeting scheduled for 6/12/19.
