### ISSUE TITLE
mobile view - menu slide-out slides under flood tools

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/fim-js#293]
I think it should slide over - that's the convention I've noticed using mobile apps.
![image](https://user-images.githubusercontent.com/12058013/53640613-8e7e1080-3bfa-11e9-991e-5e68995b294f.png)

**Comment by njestes** [comment]
Agreed. @HansVraga it was closed by default right? just making sure the only way it is open is that the user had to click the menu icon. That way we know it should also be clear how they can close it.

**Comment by HansVraga** [comment]
Yes, it was closed by default - I would think it's clear how to close it once again.
