### ISSUE TITLE
uncheck 'View Satellite Imagery' if user selects a different basemap in the sidebar

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/fim-js#294]
Not a big deal, but some behavior I noticed -- the 'View Satellite Imagery' in the popup doesn't become unchecked if a user selects a different basemap in the sidebar

**Steps to reproduce**: 

1. Click on any site
2. In the popup, check the box for 'View Satellite Imagery'
3. Select a different basemap from the basemap sidebar

**Comment by njestes** [comment]
fixed with #299
