### ISSUE TITLE
Opacity icon not working as expected; doesn't change opacity

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/fim-js#295]
![image](https://user-images.githubusercontent.com/23640741/53656332-f8111580-3c20-11e9-8cdd-c6c27e926f23.png)

Is that supposed to have an opacity slider on click? At the moment, clicking it just toggles the layer.

**Comment by njestes** [comment]
@lprivette good pick up, but we do have this as an issue already, so I'll close it out here.
