### ISSUE TITLE
what if: we let the users post their own web services of GIS layers (vector, raster...) for the review mapper portion.

### ISSUE THREAD

**Issue by mhkim01** [USGS-WiM/fim-js#302]
This is just an idea after I heard about people (StreamStats?) planning to use sciencebase web services capability.  So, that users can manage their own GIS layers and minimize the DB management from us/me. I have been getting requests lately wanting multiple reloads of GIS layers which are slightly different versions of each other. There are some valid reasons for these versions and we should do them since it's much easier to review them on the mapper environment. I am just trying to get a dialogue started so that users do not have to wait on me when I am on AL like this week. Hope this all make sense to y'all.

**Comment by mhkim01** [comment]
https://www.sciencebase.gov/about/content/sciencebase-geospatial-services

**Comment by njestes** [comment]
no action on this for now
