### ISSUE TITLE
FIM for entire Lake Champlain NY/VT has issues loading maps.

### ISSUE THREAD

**Issue by mhkim01** [USGS-WiM/fim-js#308]
https://wimcloud.usgs.gov/apps/FIMReview/FloodInundationMapper.html?siteno=04295000

It is the largest area we have ever loaded on the mapper as far as I can remember. It is stuck at loading wheel. I thought I double check all the input data and no clue why this is happening. The gage is NOT a streamgage; it's a lake gage if that makes any difference. Ahhh, that might be it. This gage does not serve gage height nor discharge; it serves other parameters. see link below.

https://waterdata.usgs.gov/nwis/uv/?site_no=04295000&agency_cd=USGS

**Comment by njestes** [comment]
@mhkim01 We could probably eventually serve up this kind of library, but I thought real-time gage height was a requirement for all FIM libraries.

**Comment by mhkim01** [comment]
The policy memo specifically mentions streamgages as requirement but when I asked for clarification from IIDD, they said the policy memo was meant to be more general to include stream and lake gages. So, we need to figure out a way to include these lake gages on the mapper.

**Comment by mhkim01** [comment]
@njestes fyi, my attempt/request at having a gage height pcode that would carry duplicate lake WS elevation for this site has been declined by the NYWSC.

**Comment by mhkim01** [comment]
@njestes folks from this project is asking if "we" made any more progress on this issue. Anything other than what was discussed on Slack on 20190426?

**Comment by njestes** [comment]
Library now loads. Need to adjust text for flood tools in a few places to reflect elevation rather than gage height

- [ ] selected gage height (flood tools tab)
- [ ] gage height where current value (flood tools tab)
- [ ] y-axis (hydrograph)

**Comment by mhkim01** [comment]
@njestes we may need to customize this FIM library even further. long story short, we need to show both NWIS and AHPS data as NGVD29 datum. when we have a moment, let's discuss.

**Comment by mhkim01** [comment]
At our next team meeting, I would like to bring up this issue again.  we need to show both NWIS and AHPS data as NGVD29 datum on the mapper. As I understand it, these FIMs has to be on the JS mapper because of all the customization?

**Comment by mhkim01** [comment]
Nick and I have come up with a planned solution which should cover both this issue and https://github.com/USGS-WiM/fim-js/issues/505. To handle special cases where sites do not use gage height, a new column called "PCODE" will be added in the sites table. All regular sites will be populated with "00065" (gage height); site with special case will have a specific PCODEs that denotes which elevation data is being used. For this particular issue, we will add PCODE of "62614" and label it appropriately on the mapper as "Lake or reservoir water surface elevation above NGVD 1929, feet" or something similar.

**Comment by mhkim01** [comment]
@njestes adjustments to the sites table has been completed as described above. let me know if you need anything else.

**Comment by mhkim01** [comment]
@njestes On the updated flood tools for this site, I like the label "Lake Water Level Elevation"; it's short but to the point. However, the word "Selected" should be deleted at following locations: just below the slider bar, in the Current Condition section, and Hydrograph y-axis label. after you fix the Selected Condition section, the last line in that section which says "Elevation" should be deleted since it will be a duplication.

**Comment by mhkim01** [comment]
![image](https://user-images.githubusercontent.com/15948427/81419412-35720c80-911c-11ea-8e54-6107096c2d4d.png)

Looking good! a couple of comments; under the slider, we should have consistent capitalization of words like other places, and add the (NGVD29) at the end. under selected conditions, "Elevation" should be changed to look same as under current conditions section.

**Comment by mhkim01** [comment]
@njestes Awesome! looks great. did not catch "n/a" last time but not critical for now; we should change it to "N/A" to be consistent some time later. i think we can go public with this. what do you think?

![image](https://user-images.githubusercontent.com/15948427/81853896-19f76f00-952b-11ea-9bbb-ff111f4c3459.png)

**Comment by njestes** [comment]
Fixed and ready for site to go public.

**Comment by mhkim01** [comment]
https://test.wim.usgs.gov/fimreview/?site_no=04295000
@njestes for some reason, the fixes you made last are no longer there on the new review mapper.

![image](https://user-images.githubusercontent.com/15948427/84045389-b704c680-a976-11ea-80c1-50eae9c7cb29.png)

**Comment by mhkim01** [comment]
it works now on the new review mapper.
