### ISSUE TITLE
depth range pop up for two GA sites does not work on the public/production mapper

### ISSUE THREAD

**Issue by mhkim01** [USGS-WiM/fim-js#309]
https://fim.wim.usgs.gov/fim/?site_no=02207120
https://fim.wim.usgs.gov/fim/?site_no=02206500

for these sites, depth range pop up does not work on the production/public mapper on either the flash or the js version. however, on the review mapper on either version, depth range pop-up works without issues.

**Comment by mhkim01** [comment]
Any progress on this? User is asking and says he has a meeting with his cooperator soon and it would be good to fix this before his meeting.

**Comment by njestes** [comment]
Another issue that has been dealt with in development. Not worth our time to update the current production version that is available, I don't think. Makes more sense to have this come when the new release happens.

@mhkim01 I think we've discussed this before, but we could have the cooperator demo with some form of the more recent mapper rather.

**Comment by mhkim01** [comment]
@njestes depends on when their meeting might be. he will let me know the exact date soon. plan b, just use the review mapper.

**Comment by mhkim01** [comment]
@njestes A user is curious why this issue had occurred and how you have fixed in the new mapper. I am sort of curious too...
