### ISSUE TITLE
Discharge unit shown as feet; it should be cfs

### ISSUE THREAD

**Issue by mhkim01** [USGS-WiM/fim-js#311]
on https://fim.wim.usgs.gov/fim/ app, current discharge is shown with unit of feet; it should be in cfs. please check the other apps as well; test.wim.usgs.gov/fim shows it as fps; it should be cfs.
![image](https://user-images.githubusercontent.com/15948427/55816309-fceaa400-5abf-11e9-8f18-741add4729fc.png)

**Comment by njestes** [comment]
This is already fixed in our latest development version. Will close because it's going to be fixed when released.
