### ISSUE TITLE
unable to re-publish sites or suppLyrs services

### ISSUE THREAD

**Issue by mhkim01** [USGS-WiM/fim-js#312]
and unable to restart those services either. looking at the past chats on slack, we ended up restarting the whole AGS service, correct?

**Comment by njestes** [comment]
@mhkim01 that sounds right. Let me know if you want me to take care of that

**Comment by mhkim01** [comment]
@njestes  i have several sites i am currently working on so please do. thank you!

**Comment by mhkim01** [comment]
@njestes yup that worked. my script ran without any issues. thanks.
