### ISSUE TITLE
more_info tab for two site matrix does not pop-up before flood tools tab

### ISSUE THREAD

**Issue by mhkim01** [USGS-WiM/fim-js#313]
not critical but something to fix in the near future. more_info tab should pop-up first no matter what type of sites.
https://wimcloud.usgs.gov/apps/FIM/FloodInundationMapper.html?siteno=01014000
https://wimcloud.usgs.gov/apps/FIMReview/FloodInundationMapper.html?siteno=07377300

**Comment by njestes** [comment]
@mhkim01 Just like some of the other issues, I think we'll only be making sure this works in fim-js. Are you finding the same behavior there?

**Comment by mhkim01** [comment]
I did check the https://test.wim.usgs.gov/fim/ and same thing happens there too. is there another app that i can check multisites and review sites?

**Comment by njestes** [comment]
Fixed for fim-js. Also wasn't working for single sites, so took care of that too.
