### ISSUE TITLE
Discharge showing a value for some stage only sites

### ISSUE THREAD

**Issue by njestes** [USGS-WiM/fim-js#317]
https://fim.wim.usgs.gov/fim/?site_no=07019130

https://waterdata.usgs.gov/nwis/uv?site_no=07019130

![image](https://user-images.githubusercontent.com/5325440/56826566-69c8a280-6811-11e9-88b8-25455bc02719.png)

**Comment by njestes** [comment]
@mhkim01 I think this is fixed now. Can you check some sites to verify that?

**Comment by mhkim01** [comment]
looks like it's working. i can check the single site library. but others are two site library and those are stuck at loading splash screen.
![image](https://user-images.githubusercontent.com/15948427/57528982-bdeb8080-7301-11e9-8dec-a8f071dde0d1.png)

**Comment by njestes** [comment]
The initial fix broke some 2-site libraries, but I think it's fixed now with #331
