### ISSUE TITLE
For all 2-site FIMs: in the NWS Prediction tab, hyperlink to the secondary NWS site web page is set to the primary NWS site web page.

### ISSUE THREAD

**Issue by mhkim01** [USGS-WiM/fim-js#323]
https://github.com/USGS-WiM/FIM/issues/144 
This one was on the FIM repo and wanted to make sure we tackle it for js-mapper, if that was not done already.

**Comment by njestes** [comment]
![image (1)](https://user-images.githubusercontent.com/5325440/57324929-c94e6a00-70bd-11e9-8299-f00246ed6ad4.png)

**Comment by mhkim01** [comment]
second should go to https://water.weather.gov/ahps2/hydrograph.php?wfo=LIX&gage=magl1
and it is entered that way in the fim_sites point features.
