### ISSUE TITLE
need to add 'historical flooding' tab to the new release.

### ISSUE THREAD

**Issue by mhkim01** [USGS-WiM/fim-js#330]
- [x] Top Ten (screenshot 1)

- [x] Complete Record (Annual Flood Peaks - screenshot 2)

- [x] click to snap flood tools to value (like Hydrograph)

one of the more popular/informative tabs we had on the flash mapper. we only had it for single site  libraries but maybe we can add it to the multi-site library too?

![image](https://user-images.githubusercontent.com/15948427/57549917-d2943c80-7332-11e9-8ecd-f65a79b1e7b7.png)

**Comment by HansVraga** [comment]
![image](https://user-images.githubusercontent.com/12058013/62710380-ce70cd00-b9bc-11e9-9480-e160311d9e12.png)

**Comment by HansVraga** [comment]
Example NWIS flood peaks page, linked to at the bottom: https://waterdata.usgs.gov/nwis/inventory?agency_code=USGS&site_no=14211500

**Comment by njestes** [comment]
Will add multi-sites soon, but for now it should be in a spot that will replace all functionality on the old Flash mapper. Will create a new ticket for the multi-site scenario.
