### ISSUE TITLE
Can't open a library in GA

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/fim-js#362]
A library in Georgia won't currently open in the test site. Creating issue to make sure to remember to check it after all current changes are implemented.

![mapper with imagery](https://user-images.githubusercontent.com/12058013/62321617-ac30f980-b468-11e9-9fc0-3d1c337469cd.PNG)

**Comment by HansVraga** [comment]
Opens now, but get error message: 
https://test.wim.usgs.gov/fim/?site_no=02206500

**Comment by njestes** [comment]
@HansVraga this one looks good to me. Closing for now. Open 'er up if you're still seeing broken stuff.
