### ISSUE TITLE
(DISK Space increase request - see comments) unable to update SQL entries for print product text on FIM server

### ISSUE THREAD

**Issue by mhkim01** [USGS-WiM/fim-js#383]
when the C: drive space on the fim.wim.usgs.gov server fills up (this happens often), i can not fire up the MS SQL server for entering print product text. may need to increase the C: drive size.

**Comment by njestes** [comment]
An increase of 40 GB which should put it at around 100GB would be good.

**Comment by HansVraga** [comment]
fim.wim.usgs.gov

**Comment by HansVraga** [comment]
updated title

**Comment by aaronstephenson** [comment]
@DanielJBeckman could you take this one please?

**Comment by DanielJBeckman** [comment]
Gonna expand C and initiate a kill_temp.bat. Will do this at 6PM MST to avoid headaches when I bring the server down to expand C.

**Comment by DanielJBeckman** [comment]
FIM server C: volume boosted to 100 GiB. Not going to script a temp_kill() at this time.

**Comment by mhkim01** [comment]
fim.wim.usgs.gov server still has 60 GB on C: drive with no free space. Please increase to 100 GB. currently, unable to work with MS SQL server due to no space in C:

**Comment by mhkim01** [comment]
![image](https://user-images.githubusercontent.com/15948427/69358068-3ee1e800-0c54-11ea-9cb9-d54ef870cf6b.png)

**Comment by aaronstephenson** [comment]
Looks like the volume was increased to 100GB, but the Windows C drive was not extended to use the extra space. So I just did that.

**Comment by mhkim01** [comment]
Awesome! Thanks.
