### ISSUE TITLE
Can't click on library

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/fim-js#401]
Location circled below doesn't allow me to click on it. I noticed that unlike the other libraries, I don't get the mouse icon change from pointer to finger.
![image](https://user-images.githubusercontent.com/12058013/64046125-a9412b80-cb30-11e9-984c-08fb8e19313f.png)

**Comment by njestes** [comment]
I think this is because the 'print' layer I use to get the sites on to the print product has a different layer definition, so I just need to match it to the 'real' layer so that only fim sites are showing in that layer. I'll look into it.

**Comment by njestes** [comment]
☝️ that was it. fixed.
