### ISSUE TITLE
Go through user guide copy/content

### ISSUE THREAD

**Issue by mitchas** [USGS-WiM/fim-js#404]
Some of the text needs to be changed to make sense with UI changes.

Also there are several unused screenshots that were in the project - did we remove the user guide instructions for the slider, minimized Flood tools, etc?

**Comment by HansVraga** [comment]
- [ ] "Using the Explanation" needs rework. Drafting language below:

> The Explanation explains the symbols, patterns, and colors of the visible data layers on the map.

![image](https://user-images.githubusercontent.com/12058013/67509744-4f08a680-f659-11e9-97f1-5e17f1273be2.png)

- [ ] "Adjusting Popup Position" I think could be changed to "Managing Flood Tools Popup". A screenshot of the flood tools pop-up title area with the minimize and close icons would be helpful.
 Drafting language below:
>The Flood Tools pop-up window can be moved by clicking the title area and dragging the window. The window can be minimized by clicking the 'collapse' icon. It can be expanded once again with the 'expand' icon. The flood tools can be closed by clicking the 'X' icon.

![image](https://user-images.githubusercontent.com/12058013/67510449-95123a00-f65a-11e9-803d-4d4621de5b9c.png)

- [ ] Add a "Gage Height Slider" Section with a screenshot of the slider. Draft Language:

> The Gage Height Slider allows the user to select a gage height and see corresponding flood extent and related information. Selecting 'View grids' will color code the inundated area, with values given in explanation. Selecting 'View Satellite Imagery" will toggle the basemap to Satellite Imagery.

- [ ] Add a "Zoom to Location" Section with text 

> Selecting 'Zoom to location' will fit the interactive map window to display the extent of the flood library selected.

- [ ] "Site info & Conditions" - This language needs to change. 
>This section shows current conditions at the streamgage(s) as well as the selected conditions based on the setting of the Gage Height Slider(s). 
![image](https://user-images.githubusercontent.com/12058013/67511114-d22afc00-f65b-11e9-9679-21cd6eba268d.png)

- [ ] "More Info Tab" - language change. Draft:
>Displays optional additional information applicable for this site.
![image](https://user-images.githubusercontent.com/12058013/67513112-c7726600-f65f-11e9-8ec7-0bd1dfddb3e3.png)

- [ ] "Hydrograph" - language change. Draft:
>Displays the observed and predicted gage height/stage data. Click/Tap on the hydrograph to adjust the Gage Height Slider.
![Uploading image.png…]()

**Comment by HansVraga** [comment]
I've made my pass! @mhkim01 any thoughts on the text changes I made above?

**Comment by mhkim01** [comment]
@HansVraga i will give it a better looksy when i have some uninterrupted time tomorrow; there seem to be a stream of folks visiting my office today...

**Comment by mhkim01** [comment]
@HansVraga @njestes your suggestions look good to me. no other comments at this time.

**Comment by njestes** [comment]
@mitchas text changes implemented for all elements, left two unchecked that need new images.
