### ISSUE TITLE
Being denied yet again on AWS console for WIM main account

### ISSUE THREAD

**Issue by njestes** [USGS-WiM/fim-js#414]
user: njestes@usgs.gov

**Comment by HansVraga** [comment]
@DanielJBeckman can you help with this?

**Comment by HansVraga** [comment]
Sorry, I'm slow on the uptake here, turns out there isn't an issue to help with!

**Comment by HansVraga** [comment]
🔫 n/m there is an issue!

**Comment by DanielJBeckman** [comment]
I bet you're wrong about that. It's just working at the moment.
