### ISSUE TITLE
unable to publish grid services on fimnew.wim.usgs.gov

### ISSUE THREAD

**Issue by mhkim01** [USGS-WiM/fim-js#426]
grid_4 got published OK, 3, 2, and 1 are having issues...fimnew.wim might need a reboot?

![image](https://user-images.githubusercontent.com/15948427/66074972-7ff92e00-e528-11e9-9db6-38925521c861.png)

**Comment by njestes** [comment]
We can definitely do a restart to see if that helps. @mhkim01, did you check for GP Results Window to see if there was anything useful?

**Comment by mhkim01** [comment]
GP results window is not telling me anything useful...
![image](https://user-images.githubusercontent.com/15948427/66139186-f56b0a00-e5cd-11e9-9688-5c2b18ea9c1c.png)

**Comment by njestes** [comment]
temporarily solved (maybe permanently) by moving data to fimnew and publishing directly on FIMNEW with an ArcGIS Server Data Store reference rather than packing and transferring the data during publication.
