### ISSUE TITLE
Issues at Arnold and Fenton, MO

### ISSUE THREAD

**Issue by mhkim01** [USGS-WiM/fim-js#428]
https://test.wim.usgs.gov/fim/?site_no=07019300
https://test.wim.usgs.gov/fim/?site_no=07019210
these issues are applicable to both of these sites: on the secondary site slider (on the right), can coloring of flood stages be independent of the flood stages mapped? flood stages were mapped intervals of 4 ft or more for the secondary site. And there should not be any extended rating color since the top of curve was not defined. Are the colors on the hydrograph independent of flood stages mapped? It looks like the secondary site hydrograph (one on the bottom) is also controlling the slider for the primary site (on the left) when clicking on the graph line values.
![image](https://user-images.githubusercontent.com/15948427/66222754-dc328e00-e69f-11e9-916d-a12bb24bf287.png)

**Comment by HansVraga** [comment]
The issues are hard to describe but apparent when you play with the sliders and the hydrograph; compare the color coding in the hydrograph with that of the height selector bars.

**Comment by njestes** [comment]
fixed slider issue. @mitchas I'll leave the colors to you

**Comment by njestes** [comment]
@mitchas I think I know what's going on with the slider flood colors. Let's discuss tomorrow (11/5). 

In the meantime, there is an issue with the selected gage height value, etc for the first slider not adjusting when you click on the second slider. Click a large value on the second slider and the first slider will adjust and show the correct map, but that value isn't reflected on the flood tools. Image below. Can you take a look at that?

![image](https://user-images.githubusercontent.com/5325440/68169903-a55fca00-ff22-11e9-915c-c525849084b8.png)

**Comment by njestes** [comment]
I think this may be solved now. Would appreciate your eyes one it @mitch-wim @mhkim01 @HansVraga

**Comment by mhkim01** [comment]
Looking great! However, for the secondary site, the slider colors/categories does not match the hydrograph colors/categories which seems to be correct. This maybe due to mapping intervals for the secondary site which varies from 4ft - 12ft interval (ie jumps from 14ft, 26ft, 30ft, 34ft...so on). The fix needs to be applied to both Arnold and Fenton. 

![image](https://user-images.githubusercontent.com/15948427/72369622-7e660700-36ce-11ea-85ec-484cbeaf1e59.png)
