### ISSUE TITLE
selected discharge and altitude are not shown on flood tool window

### ISSUE THREAD

**Issue by mhkim01** [USGS-WiM/fim-js#430]
we used to show these on the flash mapper for single gage locations. did we decided not to show them anymore?

**Comment by njestes** [comment]
I don't remember whether that was a decision or was just an oversight. @hans any idea?

**Comment by HansVraga** [comment]
Discussion on this:
We're going to look to add "Selected Discharge" paired with anywhere we are showing "Selected gage Height";

We're going to add "Selected Altitude" to the "Site Info and Conditions" Tab.

**Comment by HansVraga** [comment]
For the "Site Info & Conditions tab" Mirror the minimized stuff above, and also add "Altitude" to selected Conditions.

**Comment by njestes** [comment]
> Also remove full site names from top bar, add site numbers to table, and show full name on hover

this is being tracked in #435
