### ISSUE TITLE
issues at Johnson Creek at Sycamore

### ISSUE THREAD

**Issue by mhkim01** [USGS-WiM/fim-js#431]
https://test.wim.usgs.gov/fim/?site_no=14211500
colors representing flood stages are incorrect. NWS web page does not report moderate flood stage (red), so if something is missing, don't show colors? like flash mapper does?
![image](https://user-images.githubusercontent.com/15948427/66509305-c575a800-eaa0-11e9-90f7-5bd8e28180e8.png)

**Comment by njestes** [comment]
@mhkim01 for this, are you thinking we shouldn't show any colors at all? or that we should only show the colors we have?

**Comment by mhkim01** [comment]
i can't remember why we decided not to show any colors on the flash mapper. if we can show colors of categories to match NWS, that would be OK too. 
![image](https://user-images.githubusercontent.com/15948427/66652526-ed315100-ec03-11e9-9ddd-411105279321.png)

**Comment by njestes** [comment]
@mitchas  I think we should go with showing the colors. Can you take a stab at this?
