### ISSUE TITLE
Title of the print page should be in bold font and within the text margin

### ISSUE THREAD

**Issue by mhkim01** [USGS-WiM/fim-js#434]
@njestes printing seem fast and stable. please see example below.
![image](https://user-images.githubusercontent.com/15948427/67211876-748f7900-f3e9-11e9-94d6-164bd8df0cbd.png)

**Comment by njestes** [comment]
@mhkim01 Bold shouldn't be an issue, but I had to write it outside the margins, because we had a few titles that were too long to fit within the standard margins. Maybe we can discuss options or alternate title syntax that will use less text.

**Comment by njestes** [comment]
remove everything starting with "... at the U.S. Geological ..." from the titles for page 1 and 2

![image](https://user-images.githubusercontent.com/5325440/67225968-00ed6c00-f3e9-11e9-999c-694199517d91.png)

**Comment by njestes** [comment]
add state to page 2 map title and site no to page 2 map subtitle

**Comment by njestes** [comment]
@mhkim01 closing until you find something I missed.
