### ISSUE TITLE
Title of the flood tools window should have a list of site numbers for multi-site libraries

### ISSUE THREAD

**Issue by mhkim01** [USGS-WiM/fim-js#435]
when viewing multi-site library, only one site name is listed (which ever site a user clicks on). it seems confusing? the flash mapper shows list of site numbers in order of primary, secondary, and so on. i think we should follow that rule.
![image](https://user-images.githubusercontent.com/15948427/67212631-ab19c380-f3ea-11e9-9a46-9c874dd474b7.png)

**Comment by njestes** [comment]
@mhkim01 please check this out on 10/23 if you have a minute. Let me know what you think.

**Comment by njestes** [comment]
from Mitch: remove full site names from top bar, add site numbers to table, and show full name on hover

from Nick: only remove full site names for multi sites, site nos are already in the table, so can just be the tooltip text that's added now
