### ISSUE TITLE
Set up Chris Sanocki with necessary creds to perform FIM library manager job (same as Moon, they are transitioning the role)

### ISSUE THREAD

**Issue by njestes** [USGS-WiM/fim-js#453]

**Comment by njestes** [comment]
Here's a document that Moon put together with the various machines, S3 buckets, etc that he needs to perform his job. Not all of it applies to Sysops. Contact @mhkim01 or @njestes for any clarifications.

[mkim_cred_list.xlsx](https://github.com/USGS-WiM/fim-js/files/3860441/mkim_cred_list.xlsx)

**Comment by mhkim01** [comment]
Here is an updated version of that list above.
[mkim_creds_list.xlsx](https://github.com/USGS-WiM/fim-js/files/3860470/mkim_creds_list.xlsx)

**Comment by mhkim01** [comment]
Would it be possible to have this issue resolved before the end of this week? I am trying to set up a time to walk through procedures with Chris before the end of next week. Thanks.

**Comment by aaronstephenson** [comment]
Credentials send to Chris in an email.
