### ISSUE TITLE
Peachtree Creek at Atlanta multi-site FIM library does not load

### ISSUE THREAD

**Issue by mhkim01** [USGS-WiM/fim-js#456]
https://test.wim.usgs.gov/fim/?site_no=02336300

**Comment by HansVraga** [comment]
2020-01-08 Issue remains on test site. Clicking either 02336490 or 02336300 leads to loading loop.

**Comment by HansVraga** [comment]
2020-01-08 Site now loads, but NWS stages do not work.

**Comment by njestes** [comment]
@HansVraga does this work for you now?

**Comment by HansVraga** [comment]
Appears to on Mobile

**Comment by njestes** [comment]
![image](https://user-images.githubusercontent.com/5325440/73485239-9b017080-4357-11ea-8573-5d6ebdd1903e.png)

need to fix 'undefined' link for NWS site id. Need to change to 'None' with no link

**Comment by HansVraga** [comment]
Moon is going to take a look at the data table
