### ISSUE TITLE
investigate 2-site libraries

### ISSUE THREAD

**Issue by njestes** [USGS-WiM/fim-js#467]
Possible issue with slider one and its affect on the flood polys. Doesn't seem to update in the map.

**Comment by njestes** [comment]
I think this may be solved now. Would appreciate your eyes one it @mitch-wim @mhkim01 @HansVraga 

Going to make the same comment on the more specific case of Arnold/Fenton

**Comment by HansVraga** [comment]
I feel like this is ready to be closed at this point.
