### ISSUE TITLE
explanation box shows same item twice

### ISSUE THREAD

**Issue by mhkim01** [USGS-WiM/fim-js#495]
![image](https://user-images.githubusercontent.com/15948427/76120067-b9920180-5fbe-11ea-899c-bb3c34435a2f.png)

**Comment by mhkim01** [comment]
i got it show same item twice by checking and unchecking include area of uncertainty and view depth grid boxes.

not sure why we need to say "...two sites" at the end of the item explanation. i think we can delete "two sites" part.

**Comment by njestes** [comment]
the two sites thing is driven by needing a unique layer name for 2 site vs single sites, but we may be able to work around it, if it's an issue

**Comment by mhkim01** [comment]
or just hide the second green box without the "two sites" at the end.

**Comment by mhkim01** [comment]
look like this one is fixed too.
