### ISSUE TITLE
for multi-site FIMs, when clicking on view depth grid button, it always snaps to first/lowest depth grid

### ISSUE THREAD

**Issue by mhkim01** [USGS-WiM/fim-js#502]
both two and three site FIMs do this. no matter where the sliders are, initial click of view depth grid button, it always snaps to the first/lowest depth grid. then if you play with the slider bar, it seems to snap to the correct depth grids again.

![image](https://user-images.githubusercontent.com/15948427/76649295-ba82e000-6536-11ea-8b2f-0a0b14411e7f.png)

**Comment by njestes** [comment]
@mhkim01 I think this is fixed now. Check the test site to see if things look good for you.
