### ISSUE TITLE
USGS 04288040 WINOOSKI RIVER ABOVE CROSSETT BK AT WATERBURY,VT

### ISSUE THREAD

**Issue by mhkim01** [USGS-WiM/fim-js#506]
NO ACTION REQUIRED AT THIS TIME; https://test.wim.usgs.gov/fimreview/?site_no=04288040; will need same treatment as https://github.com/USGS-WiM/fim-js/issues/505; For this particular issue, we will add PCODE of "63160" in the sites table and label it appropriately on the mapper as "Stream water level elevation above NAVD 1988, in feet" or something similar. However, vertical datum used in NWIS and AHPS do not match for now; will need to wait for the author to fix that before making any changes. See attached email chain. 
[Mail - Kim, Moon H - Outlook_Waterbury, VT.pdf](https://github.com/USGS-WiM/fim-js/files/4450864/Mail.-.Kim.Moon.H.-.Outlook_Waterbury.VT.pdf)

**Comment by njestes** [comment]
@mhkim01 looks like this one has reached "Archived" status on the FIM Library Tracking doc. Can we close this issue?

**Comment by mhkim01** [comment]
oops, that one should be on the Draft status for now; i will change that. it was Archived but author would like to bring it back. but there are some issues with datum used on NWIS vs AHPS. so we have to wait for that to resolve first before we can go any further.

**Comment by njestes** [comment]
Closing this and can always reopen down the road if the author contacts us and the issues are resolved
