### ISSUE TITLE
USGS 05587450 Mississippi River at Grafton, IL does not load on old review mapper

### ISSUE THREAD

**Issue by mhkim01** [USGS-WiM/fim-js#513]
https://wimcloud.usgs.gov/apps/FIMReview/FloodInundationMapper.html?siteno=05587450

As far as I can tell, the data layers have been loaded and is being served on the gis.wim server for the old review mapper. We may need help from Mitch and/or Nick to figure out why Grafton is not loading on the old review mapper. 

Chris, before you sent out a note saying that these sites were ready for MO folks to check, do remember if both old and new review mappers were working properly?

**Comment by mhkim01** [comment]
I have re-checked the database on the jump server and everything seems to be in good order. still no clue on why it does not load on the old review mapper.

**Comment by njestes** [comment]
@mhkim01 did you check in with the MO folks to see if they are ok with our current workaround for the Grafton site on the old mapper?

**Comment by mhkim01** [comment]
they are planning to show old and new review mapper side by side; Historical Flood tab with old, then show rest with the new. i figured that's just as good as (and maybe simpler than) our current workaround, zoom adjustment.
