### ISSUE TITLE
FIM libraries that are in review phase is shown on public NWIS web page.

### ISSUE THREAD

**Issue by mhkim01** [USGS-WiM/fim-js#516]
https://waterdata.usgs.gov/monitoring-location/05514860/#parameterCode=00060

this particular site is still in review. the maps should NOT be shown on any public web pages. this applies to all FIM sites in review phase.

https://test.wim.usgs.gov/fimreview/?site_no=05514860

**Comment by HansVraga** [comment]
Thanks for bringing this up again Moon - I'll contact Jim Kreft and Mary Bucknell and point them here.

**Comment by HansVraga** [comment]
Latest - not a straightforward change on either end.

**Comment by HansVraga** [comment]
Working on fixing this in latest round of water pages work

**Comment by HansVraga** [comment]
@mitchas I heard addressing this was part of our internet of water project - was this taken care of in the last release?

**Comment by mitchas** [comment]
@HansVraga It's the issue I have this sprint. Hopefully will get it this week.
