### ISSUE TITLE
Add Historic Flood Info to User Guide

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/fim-js#539]
![image](https://user-images.githubusercontent.com/12058013/92037412-57307880-ed37-11ea-9e9c-83595f22781d.png)

**Comment by mitchas** [comment]
A space is in the user guide - just need some text for it.

**Comment by njestes** [comment]
@HansVraga how's this for some historic text. Feel free to edit.

"Displays annual flood peak information chronologically arranged on two charts. Top 10 Annual Flood Peaks shows the highest 10 annual flood peaks on record for the gage. Annual Flood Peaks shows the full record of annual flood peaks for the gage."
