### ISSUE TITLE
flood tools tab content not scrollable on iphone (not sure about other mobile)

### ISSUE THREAD

**Issue by njestes** [USGS-WiM/fim-js#544]

**Comment by mitchas** [comment]
@njestes I tested it on an Android phone and on an iPad (Safari and Chrome - although iPad has the full view instead of mobile) and didn't have any issues.

It's happening for you on test.wim.usgs.gov/fim/ ?

**Comment by njestes** [comment]
@mitchas yeah, still seeing it on my phone (iphone 11)
