### ISSUE TITLE
convert webcam from iframe (needed for flash) to coded in html

### ISSUE THREAD

**Issue by njestes** [USGS-WiM/fim-js#56]

**Comment by HansVraga** [comment]
Example from Flash: 
![image](https://user-images.githubusercontent.com/12058013/39645713-36475254-4fa7-11e8-8438-9500031bedb6.png)
![image](https://user-images.githubusercontent.com/12058013/39645747-50508fee-4fa7-11e8-92ea-b4edef47c175.png)

**Comment by HansVraga** [comment]
Code Snippet to help https://wim-usgs.slack.com/files/U2QBH0516/FAJGV8VFV/-.html
