### ISSUE TITLE
Boise River at Glenwood Bridge Hydrograph

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/fim-js#577]
https://fim.wim.usgs.gov/fim/?site_no=13206000

Predicted values before actual? Seems out of order. Doesn't line up with what is in NWIS

![image](https://user-images.githubusercontent.com/12058013/109720964-63738200-7b70-11eb-80f9-a4d938e60b1a.png)

**Comment by njestes** [comment]
@HansVraga Interesting. I'm not seeing the swapping of NWIS and NWS values. Also, pretty sure it's lines up with NWIS, but NWIS really zooms in on that y-axis. I'll leave this open for now. Can you check again and if you still see the values switched around, we can try to dig in and see why it's happening.

![image](https://user-images.githubusercontent.com/5325440/109889627-971ade80-7c3a-11eb-893a-5e8894f14214.png)

**Comment by HansVraga** [comment]
Oddly enough now I don't see the swap. Weird!

**Comment by HansVraga** [comment]
I'm on my phone, but also checking in test the values are no longer swapped. I guess something to keep an eye out for!
