### ISSUE TITLE
Add Vertical Datum Name

### ISSUE THREAD

**Issue by jprokopec** [USGS-WiM/fim-js#580]
Add vertical datum name to "Site Info & Conditions" tab under elevation. 

Example: 692.80 feet above NAVD88

![FIM](https://user-images.githubusercontent.com/58087084/112370389-521f2080-8cab-11eb-8005-c1053dcf5b16.PNG)

**Comment by njestes** [comment]
@jprokopec I'll can just add it the same way we have it here, if that's ok. We only started adding units when we started having datums other than NAVD88, so it'll just be a matter of updating the code to add the text and attributing all the original gages with the appropriate pcode in the services. Then things should fall into place for all the other gages. But if we should wording it with the 'above' that'll take a bit more work.

![image](https://user-images.githubusercontent.com/5325440/113026493-fbe42e80-913d-11eb-8ee6-484ab8e07dfd.png)
