### ISSUE TITLE
04189000 Findlay, OH "More Info" 

### ISSUE THREAD

**Issue by jprokopec** [USGS-WiM/fim-js#583]
Add text to "More Info" tab for site https://fim.wim.usgs.gov/fim/?site_no=04189000. 

_Floodplain boundaries shown for the Blanchard River may be inaccurate for some gage heights due to recent flood-mitigation projects completed near Findlay, Ohio._

**Comment by 09Kathy** [comment]
I was looking into this. Is this a temporary or permanent disclaimer? I was able to quickly do it in the code, if that's the route we want to go, but I'm thinking if we want to keep it around it should go in the service instead. @njestes , is there a fancy way of adding more info text in the service? I see that it's accessing the table [here](https://fim.wim.usgs.gov/arcgis/rest/services/FIMMapper/fim_add_info/MapServer), but when I try to view the table both online and in the jump drive it says I can't access it, or even view the path to where it is stored.
All the more info tabs in the mapper are working, so it's not broken - I'm definitely missing something about where the data are stored.
![image](https://user-images.githubusercontent.com/46943254/113931003-97694500-97b7-11eb-8d89-13cff06b2a76.png)

**Comment by njestes** [comment]
@09Kathy Either I'll take care of this one or we'll go over the process when we chat next
