### ISSUE TITLE
Webcam images forcing https breaks some embeds

### ISSUE THREAD

**Issue by mitchas** [USGS-WiM/fim-js#592]
Line 1613 core.js
`$("#webcamImage").attr('src', feature.attributes.WEBCAM_INFO.replace('http:', 'https:'));`

Loading St Paul webcam with HTTPS doesn't work
https://webcams.ci.stpaul.mn.us/webcams/CityHallCam/cityhall.jpg

**Comment by mitchas** [comment]
Leaving this open because it's still an issue. I did add a fallback image to load if the webcam image is unavailable - just to let the user know it failed to load.

**Comment by njestes** [comment]
Going to call it that the fallback image is good enough right now. Going foward we'll use NIMS cams for FIM sites
