### ISSUE TITLE
Gage Height - Change NAVD88 to ft

### ISSUE THREAD

**Issue by jprokopec** [USGS-WiM/fim-js#628]
Gage Height is an arbitrary number not referenced to sea level. Units should be in ft with gage height. Elevation is correct with NAVD88. 

![GageH](https://user-images.githubusercontent.com/58087084/146050731-cf8b65d3-6b80-4b30-acf9-1e48ca941dbb.PNG)
![GH](https://user-images.githubusercontent.com/58087084/146050879-8a779fe5-cf00-45b0-b34e-fda9512f8505.PNG)

I believe I only see gage height (NAVD88) in these 3 places. 

Hydrographs for reference on display of gage height and elevation
![InkedGH2_LI](https://user-images.githubusercontent.com/58087084/146051926-d29de0f4-5caa-40ca-ba5d-61c9fec3a548.jpg)

**Comment by njestes** [comment]
@jprokopec check it out at the test mapper and let me know how it looks

http://test.wim.usgs.gov/fim

**Comment by jprokopec** [comment]
@njestes Looks great! Thank you for making that change.
