### ISSUE TITLE
Add Webcam to St Paul, MN (05331000)

### ISSUE THREAD

**Issue by jprokopec** [USGS-WiM/fim-js#629]
Add USGS Webcam (https://apps.usgs.gov/sstl/camera/05331000_MN_MissR_St_Paul) to the Webcam tab for[ St Paul, MN (05331000](https://fim.wim.usgs.gov/fim/?site_no=05331000))

Please link the USGS's webcam first and then the City of St Paul's (current) webcam after.

**Comment by njestes** [comment]
Removing cam from this site
