### ISSUE TITLE
Flood Warning Triangles

### ISSUE THREAD

**Issue by jprokopec** [USGS-WiM/fim-js#681]
![stp](https://user-images.githubusercontent.com/58087084/232835655-dc682acd-ee8d-42aa-85a8-3d4de55c26cd.PNG)
It seems the flood warning colors are not populating the triangles the correct colors. At least not for St Paul.

**Comment by HansVraga** [comment]
something is caching those colors.

When I did a full refresh (press F12 on the site to open developer tools, right click the refresh button, empty cache and hard refresh) the right colors appeared.

**Comment by jprokopec** [comment]
That did work. But general public isn't going to know to do that... right?

**Comment by njestes** [comment]
Yeah, that's a strange issue. I'll look into ways to avoid the cache. 🤔

**Comment by njestes** [comment]
we'll open a new issue if it persists, but I think we're good
